wip: projects and columns realisation finished
PECHIVKO/task-manager pull request #1
Opened 2021-01-13 14:20 UTC by PECHIVKO

2021-01-13 14:49 UTC, PECHIVKO commented on project/repository/postgres/project.go
> +	err = tx.QueryRowContext(ctx, insertProjectQuery, model.Name, model.Description).Scan(&projectID)
туть

2021-01-21 09:06 UTC, eugeneradionov requested changes

2021-01-21 09:06 UTC, eugeneradionov commented on column/delivery/http/handler.go
> +	id, _ := strconv.Atoi(chi.URLParam(r, "id"))
do not ignore errors

2021-01-21 09:06 UTC, eugeneradionov commented on comment/delivery/http/handler.go
> +	input.CommentID, _ = strconv.Atoi(chi.URLParam(r, "id"))
do not ignore errors

2021-01-21 09:06 UTC, eugeneradionov commented on comment/repository/postgres/comment.go
> +	// checkForTaskExists = `select exists
remove or uncomment

2021-01-21 09:06 UTC, eugeneradionov commented on config/config.go
> +	//	MigrationsSource string `yaml:"migrations_source" validate:"required"`
remove or uncomment

2021-01-25 18:04 UTC, closed without merging